"""Common support for rules_proto_grpc Rust rules."""

load("@rules_proto_grpc//:defs.bzl", "proto_compile")
load("@rules_rust//rust:defs.bzl", "rust_common")

RustProtoInfo = provider(
    doc = "Additional information needed by Rust proto compilation rules.",
    fields = {
        "crate_name": "Name of the crate that wraps this module.",
        "declared_proto_packages": "All proto packages that this compile rule generates bindings for.",
        "declared_proto_types": "Fully-qualified proto message/enum type names this crate generates. Used to emit per-type extern_path so a single proto package can be split across several per-file crates.",
    },
)

rust_compile_attrs = [
    "declared_proto_packages",
    "declared_proto_types",
    "crate_name",
    "proto_deps",
    "deps",
]

def crate_label(name):
    """Converts a crate package name into its generated crate-universe label.

    Args:
        name: Crate package name as it appears in `Cargo.toml`.

    Returns:
        A label for the generated crate target.
    """
    return Label("@rules_proto_grpc_rust_crates//:" + name)

def proto_runtime_label():
    """Returns the public Rust proto runtime target."""
    return Label("@rules_proto_grpc_rust//rust:proto_runtime")

def implicit_protobuf_label():
    """Returns the canonical generated Rust crate for google.protobuf."""
    return Label("@rules_proto_grpc_rust//google/protobuf:protobuf_rust_proto")

RUST_RAW_IDENTIFIER_KEYWORDS = {
    "abstract": True,
    "as": True,
    "async": True,
    "await": True,
    "become": True,
    "box": True,
    "break": True,
    "const": True,
    "continue": True,
    "do": True,
    "dyn": True,
    "else": True,
    "enum": True,
    "extern": True,
    "false": True,
    "final": True,
    "fn": True,
    "for": True,
    "gen": True,
    "if": True,
    "impl": True,
    "in": True,
    "let": True,
    "loop": True,
    "macro": True,
    "match": True,
    "mod": True,
    "move": True,
    "mut": True,
    "override": True,
    "priv": True,
    "pub": True,
    "ref": True,
    "return": True,
    "static": True,
    "struct": True,
    "trait": True,
    "true": True,
    "try": True,
    "type": True,
    "typeof": True,
    "unsafe": True,
    "unsized": True,
    "use": True,
    "virtual": True,
    "where": True,
    "while": True,
    "yield": True,
}

def rust_identifier_path_segment(segment):
    """Escapes a proto package segment for a Rust path when needed."""
    if segment in RUST_RAW_IDENTIFIER_KEYWORDS:
        return "r#" + segment

    return segment

def rust_proto_package_path(package):
    """Converts a proto package into the generated Rust module path."""
    return "::".join([
        rust_identifier_path_segment(segment)
        for segment in package.split(".")
    ])

def dedupe_labels(labels):
    """Deduplicates a list of labels while preserving the first occurrence.

    Args:
        labels: Labels to deduplicate.

    Returns:
        The deduplicated labels in their original order.
    """
    seen = {}
    result = []

    for label in labels:
        key = str(label)
        if key in seen:
            continue
        seen[key] = True
        result.append(label)

    return result

def merge_rust_deps(deps, proto_deps, include_implicit_protobuf = True):
    """Merges Rust deps and legacy proto_deps into the single dependency list.

    Args:
        deps: Labels passed in the public deps attr.
        proto_deps: Labels passed in the deprecated proto_deps attr.
        include_implicit_protobuf: Whether to add the generated google.protobuf
            Rust crate automatically.

    Returns:
        A deduplicated list of labels.
    """
    merged = []
    merged.extend(deps)
    merged.extend(proto_deps)

    if include_implicit_protobuf:
        merged.append(implicit_protobuf_label())

    return dedupe_labels(merged)

def proto_package_is_ancestor_or_equal(package, declared_package):
    """Returns whether a proto package covers another package by prefix.

    Args:
        package: Candidate dependency proto package.
        declared_package: Proto package generated by the current rule.

    Returns:
        True when package is the same as declared_package or an ancestor of it.
    """
    return declared_package == package or declared_package.startswith(package + ".")

def proto_package_overlaps_declared(package, declared_packages):
    """Returns whether package would extern a locally generated package.

    Args:
        package: Candidate dependency proto package.
        declared_packages: Proto packages generated by the current rule.

    Returns:
        True when package is equal to, or an ancestor of, any declared package.
    """
    for declared in declared_packages:
        if proto_package_is_ancestor_or_equal(package, declared):
            return True

    return False

def owning_proto_package(type_name, packages):
    """Returns the longest declared package that is a prefix of type_name.

    Args:
        type_name: A fully-qualified proto type, e.g. "pkg.Msg.Nested".
        packages: The candidate declared proto packages of the owning crate.

    Returns:
        The owning package, or None if none of `packages` is a prefix.
    """
    best = None
    for package in packages:
        if type_name == package or type_name.startswith(package + "."):
            if best == None or len(package) > len(best):
                best = package
    return best

def to_snake(name):
    """Approximates prost's message-name-to-module snake_case conversion.

    Nested proto types become modules named after the enclosing message in
    snake_case (`InstructorProfile` -> `instructor_profile`). A boundary gets an
    underscore before an uppercase letter that follows a lowercase/digit, or that
    starts a new word after an acronym (the uppercase is followed by lowercase).
    """
    out = []
    length = len(name)
    for i in range(length):
        ch = name[i]
        if ch.isupper():
            prev = name[i - 1] if i > 0 else ""
            nxt = name[i + 1] if i + 1 < length else ""
            boundary = i > 0 and (prev.islower() or prev.isdigit() or (prev.isupper() and nxt.islower()))
            if boundary:
                out.append("_")
            out.append(ch.lower())
        else:
            out.append(ch)
    return "".join(out)

def rust_extern_type_path(type_name, owner_package, escaped):
    """Builds the Rust module path for a proto type owned by another crate.

    Segments after the owning package are message nesting: all but the final type
    name become snake_case modules, matching prost's generated layout. `escaped`
    raw-identifier-escapes keyword segments for generators (tonic) that parse
    their own output; prost and pbjson want the raw path and the crate fixer
    escapes their output afterwards.
    """
    segments = owner_package.split(".")
    nesting = type_name[len(owner_package) + 1:].split(".")
    for parent in nesting[:-1]:
        segments.append(to_snake(parent))
    segments.append(nesting[-1])
    if escaped:
        segments = [rust_identifier_path_segment(segment) for segment in segments]
    return "::".join(segments)

def rust_plugin_enabled(ctx, plugin_name):
    """Returns whether a Rust protoc plugin is enabled on this compile rule."""
    for plugin in getattr(ctx.attr, "_plugins", []):
        if plugin.label.name == plugin_name:
            return True

    return False

def rust_proto_library_forward_impl(ctx):
    """Forwards a generated rust_library while adding RustProtoInfo.

    Args:
        ctx: Rule context.

    Returns:
        Providers from the underlying rust_library plus RustProtoInfo.
    """
    actual = ctx.attr.actual
    compilation = ctx.attr.compilation[RustProtoInfo]

    providers = [
        actual[DefaultInfo],
        actual[rust_common.crate_info],
        actual[rust_common.dep_info],
        compilation,
    ]

    return providers

rust_proto_library_forward = rule(
    doc = "Forwards a generated rust_library and exposes RustProtoInfo on the public target.",
    implementation = rust_proto_library_forward_impl,
    attrs = {
        "actual": attr.label(
            doc = "The underlying rust_library target to forward.",
            mandatory = True,
        ),
        "compilation": attr.label(
            doc = "The Rust proto compile target providing RustProtoInfo.",
            providers = [RustProtoInfo],
            mandatory = True,
        ),
    },
)

def rust_proto_compile_impl(ctx):
    """Implements Rust proto and gRPC compile rules.

    Rust dependencies are crate-scoped, while proto dependencies are
    package-scoped. This implementation converts `proto_deps` metadata into
    `extern_path` options for the Rust protobuf plugin so generated code can
    refer to types from dependent Rust crates.

    Args:
        ctx: Rule context.

    Returns:
        The providers returned by `proto_compile` plus `RustProtoInfo`.
    """
    # extern_path teaches prost/tonic/serde how to NAME a dependency's types.
    # Keyword path segments (a proto package like `match` or `type`) need raw
    # identifiers (`r#match`) to be valid Rust. prost and pbjson want the RAW path
    # and mangle a pre-escaped `r#` into `r_`; the crate fixer rewrites their
    # `::match::` output to `::r#match::` afterwards. tonic instead parses its own
    # output during codegen, so it must receive already-escaped paths. Hence two
    # forms: raw for prost/serde, escaped for tonic.
    externs = []
    grpc_externs = []

    # Only the prost message plugin also SKIPS regenerating externed types. pbjson
    # (serde) generates a serde impl for every type in the included packages --
    # including a sibling crate's types that live in a package this crate also
    # declares -- which orphan-conflicts with the impl in the owning crate.
    # `exclude` (a segment-prefix filter, so it also covers nested types) tells
    # pbjson not to regenerate serde for externed types.
    serde_excludes = []
    rust_deps = []
    rust_deps.extend(getattr(ctx.attr, "deps", []))
    rust_deps.extend(getattr(ctx.attr, "proto_deps", []))

    declared_packages = ctx.attr.declared_proto_packages
    local_types = {t: True for t in getattr(ctx.attr, "declared_proto_types", [])}
    seen_packages = {}
    seen_types = {}
    for dep in rust_deps:
        if RustProtoInfo not in dep:
            continue

        proto_info = dep[RustProtoInfo]
        dep_crate = proto_info.crate_name
        dep_types = getattr(proto_info, "declared_proto_types", [])

        if dep_types:
            # Per-type extern. A first-party proto package is split across one
            # crate per file, so the package as a whole does not map to a single
            # crate: every type must be externed to the specific crate that owns
            # it. This is required both for sibling files in a package this crate
            # also declares AND for imported packages that are themselves split.
            # Skipping this crate's own types leaves them to be generated locally.
            for type_name in dep_types:
                if type_name in local_types or type_name in seen_types:
                    continue
                owner_package = owning_proto_package(type_name, proto_info.declared_proto_packages)
                if owner_package == None:
                    continue
                seen_types[type_name] = True
                externs.append("extern_path=.{}=::{}::{}".format(
                    type_name,
                    dep_crate,
                    rust_extern_type_path(type_name, owner_package, False),
                ))
                grpc_externs.append("extern_path=.{}=::{}::{}".format(
                    type_name,
                    dep_crate,
                    rust_extern_type_path(type_name, owner_package, True),
                ))
                serde_excludes.append("exclude=." + type_name)
        else:
            # Whole-package extern fallback for single-crate dependencies that do
            # not enumerate their types (e.g. the vendored google.* wrappers,
            # whose packages never overlap first-party ones).
            for package in proto_info.declared_proto_packages:
                if proto_package_overlaps_declared(package, declared_packages):
                    continue
                if package in seen_packages:
                    continue
                seen_packages[package] = True
                externs.append("extern_path={}=::{}::{}".format(
                    "." + package,
                    dep_crate,
                    package.replace(".", "::"),
                ))
                grpc_externs.append("extern_path={}=::{}::{}".format(
                    "." + package,
                    dep_crate,
                    rust_proto_package_path(package),
                ))
                serde_excludes.append("exclude=." + package)

    options = dict(ctx.attr.options)
    proto_plugin = "@rules_proto_grpc_rust//:rust_proto_plugin"
    serde_plugin = "@rules_proto_grpc_rust//:rust_serde_plugin"
    grpc_plugin = "@rules_proto_grpc_rust//:rust_grpc_plugin"
    if rust_plugin_enabled(ctx, "rust_proto_plugin"):
        options[proto_plugin] = options.get(proto_plugin, []) + externs
    if rust_plugin_enabled(ctx, "rust_serde_plugin"):
        options[serde_plugin] = options.get(serde_plugin, []) + externs + serde_excludes
    if rust_plugin_enabled(ctx, "rust_grpc_plugin"):
        options[grpc_plugin] = options.get(grpc_plugin, []) + grpc_externs

    compile_result = proto_compile(
        ctx,
        options,
        getattr(ctx.attr, "extra_protoc_args", []),
        ctx.files.extra_protoc_files,
    )

    return compile_result + [RustProtoInfo(
        declared_proto_packages = ctx.attr.declared_proto_packages,
        declared_proto_types = getattr(ctx.attr, "declared_proto_types", []),
        crate_name = ctx.attr.crate_name or ctx.attr.name,
    )]
