"""Common support for rules_proto_grpc Rust rules."""

load("@protobuf//bazel/common:proto_info.bzl", "ProtoInfo")
load("@rules_proto_grpc//:defs.bzl", "proto_compile")
load("@rules_proto_grpc//internal:common.bzl", "descriptor_proto_path")
load("@rules_rust//rust:defs.bzl", "rust_common")

RustProtoInfo = provider(
    doc = "Additional information needed by Rust proto compilation rules.",
    fields = {
        "crate_name": "Name of the crate that wraps this module.",
        "declared_proto_packages": "All proto packages that this compile rule generates bindings for.",
        "proto_files": "Proto file names (as protoc names them) whose messages/enums this crate generates. Dependents pass these to the generators' `crate_for_file` parameter so a proto package can be split across one crate per file. Empty for aggregate crates (e.g. the google.* wrappers) and grpc crates, which own no message types.",
    },
)

rust_compile_attrs = [
    "declared_proto_packages",
    "crate_name",
    "proto_deps",
    "deps",
]

def crate_label(name):
    """Converts a crate package name into its generated crate-universe label.

    Args:
        name: Crate package name as it appears in `Cargo.toml`.

    Returns:
        A label for the generated crate target.
    """
    return Label("@rules_proto_grpc_rust_crates//:" + name)

def proto_runtime_label():
    """Returns the public Rust proto runtime target."""
    return Label("@rules_proto_grpc_rust//rust:proto_runtime")

def implicit_protobuf_label():
    """Returns the canonical generated Rust crate for google.protobuf."""
    return Label("@rules_proto_grpc_rust//google/protobuf:protobuf_rust_proto")

RUST_RAW_IDENTIFIER_KEYWORDS = {
    "abstract": True,
    "as": True,
    "async": True,
    "await": True,
    "become": True,
    "box": True,
    "break": True,
    "const": True,
    "continue": True,
    "do": True,
    "dyn": True,
    "else": True,
    "enum": True,
    "extern": True,
    "false": True,
    "final": True,
    "fn": True,
    "for": True,
    "gen": True,
    "if": True,
    "impl": True,
    "in": True,
    "let": True,
    "loop": True,
    "macro": True,
    "match": True,
    "mod": True,
    "move": True,
    "mut": True,
    "override": True,
    "priv": True,
    "pub": True,
    "ref": True,
    "return": True,
    "static": True,
    "struct": True,
    "trait": True,
    "true": True,
    "try": True,
    "type": True,
    "typeof": True,
    "unsafe": True,
    "unsized": True,
    "use": True,
    "virtual": True,
    "where": True,
    "while": True,
    "yield": True,
}

def rust_identifier_path_segment(segment):
    """Escapes a proto package segment for a Rust path when needed."""
    if segment in RUST_RAW_IDENTIFIER_KEYWORDS:
        return "r#" + segment

    return segment

def rust_proto_package_path(package):
    """Converts a proto package into the generated Rust module path."""
    return "::".join([
        rust_identifier_path_segment(segment)
        for segment in package.split(".")
    ])

def dedupe_labels(labels):
    """Deduplicates a list of labels while preserving the first occurrence.

    Args:
        labels: Labels to deduplicate.

    Returns:
        The deduplicated labels in their original order.
    """
    seen = {}
    result = []

    for label in labels:
        key = str(label)
        if key in seen:
            continue
        seen[key] = True
        result.append(label)

    return result

def merge_rust_deps(deps, proto_deps, include_implicit_protobuf = True):
    """Merges Rust deps and legacy proto_deps into the single dependency list.

    Args:
        deps: Labels passed in the public deps attr.
        proto_deps: Labels passed in the deprecated proto_deps attr.
        include_implicit_protobuf: Whether to add the generated google.protobuf
            Rust crate automatically.

    Returns:
        A deduplicated list of labels.
    """
    merged = []
    merged.extend(deps)
    merged.extend(proto_deps)

    if include_implicit_protobuf:
        merged.append(implicit_protobuf_label())

    return dedupe_labels(merged)

def proto_package_is_ancestor_or_equal(package, declared_package):
    """Returns whether a proto package covers another package by prefix.

    Args:
        package: Candidate dependency proto package.
        declared_package: Proto package generated by the current rule.

    Returns:
        True when package is the same as declared_package or an ancestor of it.
    """
    return declared_package == package or declared_package.startswith(package + ".")

def proto_package_overlaps_declared(package, declared_packages):
    """Returns whether package would extern a locally generated package.

    Args:
        package: Candidate dependency proto package.
        declared_packages: Proto packages generated by the current rule.

    Returns:
        True when package is equal to, or an ancestor of, any declared package.
    """
    for declared in declared_packages:
        if proto_package_is_ancestor_or_equal(package, declared):
            return True

    return False

def rust_plugin_enabled(ctx, plugin_name):
    """Returns whether a Rust protoc plugin is enabled on this compile rule."""
    for plugin in getattr(ctx.attr, "_plugins", []):
        if plugin.label.name == plugin_name:
            return True

    return False

def owned_proto_files(ctx):
    """Returns the proto file names (as protoc names them) this crate owns.

    Derived from `protos` rather than a separate attribute -- `descriptor_proto_path`
    yields exactly the name the generators match against, including for external
    protos (e.g. @googleapis). A grpc compile generates only service stubs and
    owns no message types, so it advertises nothing for dependents to extern.
    """
    if rust_plugin_enabled(ctx, "rust_grpc_plugin"):
        return []
    files = []
    for proto in ctx.attr.protos:
        proto_info = proto[ProtoInfo]
        for src in proto_info.direct_sources:
            files.append(descriptor_proto_path(src, proto_info))
    return files

def rust_proto_library_forward_impl(ctx):
    """Forwards a generated rust_library while adding RustProtoInfo.

    Args:
        ctx: Rule context.

    Returns:
        Providers from the underlying rust_library plus RustProtoInfo.
    """
    actual = ctx.attr.actual
    compilation = ctx.attr.compilation[RustProtoInfo]

    providers = [
        actual[DefaultInfo],
        actual[rust_common.crate_info],
        actual[rust_common.dep_info],
        compilation,
    ]

    return providers

rust_proto_library_forward = rule(
    doc = "Forwards a generated rust_library and exposes RustProtoInfo on the public target.",
    implementation = rust_proto_library_forward_impl,
    attrs = {
        "actual": attr.label(
            doc = "The underlying rust_library target to forward.",
            mandatory = True,
        ),
        "compilation": attr.label(
            doc = "The Rust proto compile target providing RustProtoInfo.",
            providers = [RustProtoInfo],
            mandatory = True,
        ),
    },
)

def rust_proto_compile_impl(ctx):
    """Implements Rust proto and gRPC compile rules.

    Rust dependencies are crate-scoped while proto types are package-scoped, and
    a package may be split across one crate per file. This turns each dependency's
    `RustProtoInfo` into `crate_for_file` options (or, for aggregate crates, a
    whole-package `extern_path`) so the generators reference dependency types
    through the crate that owns them instead of regenerating them.

    Args:
        ctx: Rule context.

    Returns:
        The providers returned by `proto_compile` plus `RustProtoInfo`.
    """
    # A first-party proto package is compiled as one crate per file, so the
    # package as a whole does not map to a single crate. `crate_for_file` tells
    # the prost / serde / tonic generators which crate owns each dependency proto
    # file; the generators read that file's types from the descriptor and extern
    # them (and, for serde, exclude them) using prost's own module and type
    # naming. It is a single identical opt per file across all three plugins.
    #
    # Aggregate dependencies that own a whole package in one crate (the vendored
    # google.* wrappers) advertise no `proto_files`; they fall back to a
    # whole-package `extern_path`. Keyword segments (`match`, `type`) need raw
    # identifiers: prost and pbjson take the raw path (the crate fixer rewrites
    # `::match::` to `::r#match::` afterwards) while tonic parses its own output
    # and needs it pre-escaped -- hence a raw and an escaped form.
    crate_for_file = []
    externs = []
    grpc_externs = []
    serde_excludes = []
    rust_deps = []
    rust_deps.extend(getattr(ctx.attr, "deps", []))
    rust_deps.extend(getattr(ctx.attr, "proto_deps", []))

    declared_packages = ctx.attr.declared_proto_packages
    seen_files = {}
    seen_packages = {}
    for dep in rust_deps:
        if RustProtoInfo not in dep:
            continue

        proto_info = dep[RustProtoInfo]
        dep_crate = proto_info.crate_name
        dep_files = getattr(proto_info, "proto_files", [])

        if dep_files:
            for proto_file in dep_files:
                if proto_file in seen_files:
                    continue
                seen_files[proto_file] = True
                crate_for_file.append("crate_for_file={}={}".format(proto_file, dep_crate))
        else:
            # Whole-package extern fallback for single-crate dependencies whose
            # packages never overlap first-party ones (e.g. the google.* wrappers).
            for package in proto_info.declared_proto_packages:
                if proto_package_overlaps_declared(package, declared_packages):
                    continue
                if package in seen_packages:
                    continue
                seen_packages[package] = True
                externs.append("extern_path={}=::{}::{}".format(
                    "." + package,
                    dep_crate,
                    package.replace(".", "::"),
                ))
                grpc_externs.append("extern_path={}=::{}::{}".format(
                    "." + package,
                    dep_crate,
                    rust_proto_package_path(package),
                ))
                serde_excludes.append("exclude=." + package)

    options = dict(ctx.attr.options)
    proto_plugin = "@rules_proto_grpc_rust//:rust_proto_plugin"
    serde_plugin = "@rules_proto_grpc_rust//:rust_serde_plugin"
    grpc_plugin = "@rules_proto_grpc_rust//:rust_grpc_plugin"
    if rust_plugin_enabled(ctx, "rust_proto_plugin"):
        options[proto_plugin] = options.get(proto_plugin, []) + externs + crate_for_file
    if rust_plugin_enabled(ctx, "rust_serde_plugin"):
        options[serde_plugin] = options.get(serde_plugin, []) + externs + serde_excludes + crate_for_file
    if rust_plugin_enabled(ctx, "rust_grpc_plugin"):
        options[grpc_plugin] = options.get(grpc_plugin, []) + grpc_externs + crate_for_file

    compile_result = proto_compile(
        ctx,
        options,
        getattr(ctx.attr, "extra_protoc_args", []),
        ctx.files.extra_protoc_files,
    )

    return compile_result + [RustProtoInfo(
        declared_proto_packages = ctx.attr.declared_proto_packages,
        proto_files = owned_proto_files(ctx),
        crate_name = ctx.attr.crate_name or ctx.attr.name,
    )]
