"""Common support for rules_proto_grpc Rust rules."""

load("@rules_proto_grpc//:defs.bzl", "proto_compile")
load("@rules_rust//rust:defs.bzl", "rust_common")

RustProtoInfo = provider(
    doc = "Additional information needed by Rust proto compilation rules.",
    fields = {
        "crate_name": "Name of the crate that wraps this module.",
        "declared_proto_packages": "All proto packages that this compile rule generates bindings for.",
    },
)

rust_compile_attrs = [
    "declared_proto_packages",
    "crate_name",
    "proto_deps",
    "deps",
]

def crate_label(name):
    """Converts a crate package name into its generated crate-universe label.

    Args:
        name: Crate package name as it appears in `Cargo.toml`.

    Returns:
        A label for the generated crate target.
    """
    return Label("@rules_proto_grpc_rust_crates//:" + name)

def proto_runtime_label():
    """Returns the public Rust proto runtime target."""
    return Label("@rules_proto_grpc_rust//rust:proto_runtime")

def implicit_protobuf_label():
    """Returns the canonical generated Rust crate for google.protobuf."""
    return Label("@rules_proto_grpc_rust//google/protobuf:protobuf_rust_proto")

def dedupe_labels(labels):
    """Deduplicates a list of labels while preserving the first occurrence.

    Args:
        labels: Labels to deduplicate.

    Returns:
        The deduplicated labels in their original order.
    """
    seen = {}
    result = []

    for label in labels:
        key = str(label)
        if key in seen:
            continue
        seen[key] = True
        result.append(label)

    return result

def merge_rust_deps(deps, proto_deps, include_implicit_protobuf = True):
    """Merges Rust deps and legacy proto_deps into the single dependency list.

    Args:
        deps: Labels passed in the public deps attr.
        proto_deps: Labels passed in the deprecated proto_deps attr.
        include_implicit_protobuf: Whether to add the generated google.protobuf
            Rust crate automatically.

    Returns:
        A deduplicated list of labels.
    """
    merged = []
    merged.extend(deps)
    merged.extend(proto_deps)

    if include_implicit_protobuf:
        merged.append(implicit_protobuf_label())

    return dedupe_labels(merged)

def proto_package_is_ancestor_or_equal(package, declared_package):
    """Returns whether a proto package covers another package by prefix.

    Args:
        package: Candidate dependency proto package.
        declared_package: Proto package generated by the current rule.

    Returns:
        True when package is the same as declared_package or an ancestor of it.
    """
    return declared_package == package or declared_package.startswith(package + ".")

def proto_package_overlaps_declared(package, declared_packages):
    """Returns whether package would extern a locally generated package.

    Args:
        package: Candidate dependency proto package.
        declared_packages: Proto packages generated by the current rule.

    Returns:
        True when package is equal to, or an ancestor of, any declared package.
    """
    for declared in declared_packages:
        if proto_package_is_ancestor_or_equal(package, declared):
            return True

    return False

def rust_proto_library_forward_impl(ctx):
    """Forwards a generated rust_library while adding RustProtoInfo.

    Args:
        ctx: Rule context.

    Returns:
        Providers from the underlying rust_library plus RustProtoInfo.
    """
    actual = ctx.attr.actual
    compilation = ctx.attr.compilation[RustProtoInfo]

    providers = [
        actual[DefaultInfo],
        actual[rust_common.crate_info],
        actual[rust_common.dep_info],
        compilation,
    ]

    return providers

rust_proto_library_forward = rule(
    doc = "Forwards a generated rust_library and exposes RustProtoInfo on the public target.",
    implementation = rust_proto_library_forward_impl,
    attrs = {
        "actual": attr.label(
            doc = "The underlying rust_library target to forward.",
            mandatory = True,
        ),
        "compilation": attr.label(
            doc = "The Rust proto compile target providing RustProtoInfo.",
            providers = [RustProtoInfo],
            mandatory = True,
        ),
    },
)

def rust_proto_compile_impl(ctx):
    """Implements Rust proto and gRPC compile rules.

    Rust dependencies are crate-scoped, while proto dependencies are
    package-scoped. This implementation converts `proto_deps` metadata into
    `extern_path` options for the Rust protobuf plugin so generated code can
    refer to types from dependent Rust crates.

    Args:
        ctx: Rule context.

    Returns:
        The providers returned by `proto_compile` plus `RustProtoInfo`.
    """
    externs = []
    rust_deps = []
    rust_deps.extend(getattr(ctx.attr, "deps", []))
    rust_deps.extend(getattr(ctx.attr, "proto_deps", []))

    declared_packages = ctx.attr.declared_proto_packages
    seen_packages = {}
    for dep in rust_deps:
        if RustProtoInfo not in dep:
            continue

        proto_info = dep[RustProtoInfo]
        dep_crate = proto_info.crate_name

        for package in proto_info.declared_proto_packages:
            if proto_package_overlaps_declared(package, declared_packages):
                continue
            if package in seen_packages:
                continue
            seen_packages[package] = True
            externs.append("extern_path={}=::{}::{}".format(
                "." + package,
                dep_crate,
                package.replace(".", "::"),
            ))

    options = dict(ctx.attr.options)
    proto_plugin = "@rules_proto_grpc_rust//:rust_proto_plugin"
    serde_plugin = "@rules_proto_grpc_rust//:rust_serde_plugin"
    options[proto_plugin] = options.get(proto_plugin, []) + externs
    options[serde_plugin] = options.get(serde_plugin, []) + externs

    compile_result = proto_compile(
        ctx,
        options,
        getattr(ctx.attr, "extra_protoc_args", []),
        ctx.files.extra_protoc_files,
    )

    return compile_result + [RustProtoInfo(
        declared_proto_packages = ctx.attr.declared_proto_packages,
        crate_name = ctx.attr.crate_name or ctx.attr.name,
    )]
