load("@rules_proto_grpc_rust//:defs.bzl", "rust_proto_library")
load("@rules_rust//rust:defs.bzl", "rust_test")

rust_proto_library(
    name = "common_types_rust_proto",
    declared_proto_packages = ["example.common"],
    protos = [
        "@rules_proto_grpc_example_protos//:common_types_proto",
    ],
    deps = [
        "@rules_proto_grpc_rust//google/type:money_rust_proto",
    ],
)

rust_proto_library(
    name = "person_place_rust_proto",
    declared_proto_packages = ["example.proto"],
    options = {
        "@rules_proto_grpc_rust//:rust_proto_plugin": [
            "type_attribute=.example.proto.Person=#[derive(Eq\\,Hash)]",
            "type_attribute=.example.proto.Place=#[derive(Eq\\,Hash)]",
        ],
    },
    protos = [
        "@rules_proto_grpc_example_protos//:person_proto",
        "@rules_proto_grpc_example_protos//:place_proto",
    ],
    deps = [
        ":thing_rust_proto",
    ],
)

rust_proto_library(
    name = "session_rust_proto",
    declared_proto_packages = ["example.session"],
    protos = [
        "@rules_proto_grpc_example_protos//:session_proto",
    ],
    deps = [
        "@rules_proto_grpc_rust//google/api:field_behavior_rust_proto",
        "@rules_proto_grpc_rust//google/api:resource_rust_proto",
        "@rules_proto_grpc_rust//google/type:latlng_rust_proto",
    ],
)

rust_proto_library(
    name = "event_rust_proto",
    declared_proto_packages = ["example.events"],
    protos = [
        "@rules_proto_grpc_example_protos//:event_proto",
    ],
)

rust_proto_library(
    name = "identity_rust_proto",
    declared_proto_packages = ["example.events.identity.v1"],
    protos = [
        "@rules_proto_grpc_example_protos//:identity_proto",
    ],
    deps = [
        ":event_rust_proto",
    ],
)

rust_proto_library(
    name = "thing_rust_proto",
    declared_proto_packages = ["example.proto"],
    protos = [
        "@rules_proto_grpc_example_protos//:thing_proto",
    ],
)

rust_test(
    name = "proto_runtime_test",
    srcs = ["proto_runtime_test.rs"],
    deps = [
        ":person_place_rust_proto",
        "@rules_proto_grpc_rust//rust:proto_runtime",
    ],
)

rust_test(
    name = "google_deps_test",
    srcs = ["google_deps_test.rs"],
    deps = [
        ":event_rust_proto",
        ":identity_rust_proto",
        ":session_rust_proto",
        "@rules_proto_grpc_rust//google/api:field_behavior_rust_proto",
        "@rules_proto_grpc_rust//google/protobuf:protobuf_rust_proto",
        "@rules_proto_grpc_rust//google/type:latlng_rust_proto",
        "@rules_proto_grpc_rust//rust:proto_runtime",
    ],
)
